apiVersion: v1
kind: Pod
metadata:
  name: pytorch1
spec:
  restartPolicy: Never
  containers:
  - image: pytorch_batch512
    imagePullPolicy: IfNotPresent
    name: pytorch
    command: ["sh", "-c", "python -u train.py; sleep infinity"]
    resources:
      requests:
        tencent.com/vcuda-core: "20"
        tencent.com/vcuda-memory: "20"
      limits:
        tencent.com/vcuda-core: "20"
        tencent.com/vcuda-memory: "20"
