apiVersion: v1
kind: Pod
metadata:
  name: benmark-100-maxpool
  annotations:
    tencent.com/vcuda-core-limit: "100"
spec:
  restartPolicy: Never
  containers:
  - image: maxpool1
    imagePullPolicy: IfNotPresent
    name: benchmark-100-maxpool
    command: ["sh", "-c", "python -u benchmark.py --testMaxPool --num_val=5000 --num_gpu=1 --device=T4 --restrict=100"]
    volumeMounts:
    - name: results
      mountPath: /results
    resources:
      requests:
        tencent.com/vcuda-core: "100"
      limits:
        tencent.com/vcuda-core: "100"
  volumes:
  - name: results
    hostPath:
      path: /home/sunym/sunym/data
      type: DirectoryOrCreate
