apiVersion: v1
kind: Pod
metadata:
  name: benmark-60
  annotations:
    tencent.com/vcuda-core-limit: "60"
spec:
  restartPolicy: Never
  containers:
  - image: maxpool1
    imagePullPolicy: IfNotPresent
    name: benchmark-60
    command: ["sh", "-c", "python -u benchmark.py --testConv --num_val=5000 --num_gpu=1 --device=T4 --restrict=60"]
    volumeMounts:
    - name: results
      mountPath: /results
    resources:
      requests:
        tencent.com/vcuda-core: "60"
        tencent.com/vcuda-memory: "59"
      limits:
        tencent.com/vcuda-core: "60"
        tencent.com/vcuda-memory: "59"
  volumes:
  - name: results
    hostPath:
      path: /home/sunym/sunym/data
      type: DirectoryOrCreate
