apiVersion: v1
kind: Pod
metadata:
  name: conv-test-60
  annotations:
    tencent.com/vcuda-core-limit: "60"
spec:
  restartPolicy: Never
  containers:
  - image: maxpool1
    imagePullPolicy: IfNotPresent
    name: conv-test-60
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: results
      mountPath: /results
    resources:
      requests:
        tencent.com/vcuda-core: "60"
        tencent.com/vcuda-memory: "59"
      limits:
        tencent.com/vcuda-core: "60"
        tencent.com/vcuda-memory: "59"
  volumes:
  - name: results
    hostPath:
      path: /home/sunym/sunym/data
      type: DirectoryOrCreate
