apiVersion: v1
kind: Pod
metadata:
  name: conv-test-20
  annotations:
    tencent.com/vcuda-core-limit: "20"
spec:
  restartPolicy: Never
  containers:
  - image: conv_name
    imagePullPolicy: IfNotPresent
    name: conv-test-20
    command: ["sh", "-c", "nvidia-smi -L; sleep infinity"]
    volumeMounts:
    - name: results
      mountPath: /results
    resources:
      requests:
        tencent.com/vcuda-core: "20"
        tencent.com/vcuda-memory: "59"
      limits:
        tencent.com/vcuda-core: "20"
        tencent.com/vcuda-memory: "59"
  volumes:
  - name: results
    hostPath:
      path: /home/sunym/sunym/data
      type: DirectoryOrCreate
