apiVersion: v1
kind: Pod
metadata:
  name: conv-test-80
  annotations:
    tencent.com/vcuda-core-limit: "80"
spec:
  restartPolicy: Never
  containers:
  - image: conv_name
    imagePullPolicy: IfNotPresent
    name: conv-test-80
    command: ["sh", "-c", "python -u benchmark.py --testConv --num_val=10000 --num_gpu=1 --device=T4 --restrict=80"]
    volumeMounts:
    - name: results
      mountPath: /results
    resources:
      requests:
        tencent.com/vcuda-core: "80"
        tencent.com/vcuda-memory: "59"
      limits:
        tencent.com/vcuda-core: "80"
        tencent.com/vcuda-memory: "59"
  volumes:
  - name: results
    hostPath:
      path: /home/sunym/sunym/data
      type: DirectoryOrCreate
