apiVersion: v1
kind: Pod
metadata:
  name: testbench1
  annotations:
    tencent.com/vcuda-core-limit: "100"
spec:
  restartPolicy: Never
  containers:
  - image: maxpool1
    imagePullPolicy: IfNotPresent
    name: benchmark1
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: results
      mountPath: /results
    - name: models
      mountPath: /models
    resources:
      requests:
        tencent.com/vcuda-core: "100"
        tencent.com/vcuda-memory: "59"
      limits:
        tencent.com/vcuda-core: "100"
        tencent.com/vcuda-memory: "59"
  volumes:
  - name: results
    hostPath:
      path: /home/sunym/sunym/data
      type: DirectoryOrCreate
  - name: models
    hostPath:
      path: /home/sunym/sunym/model
      type: DirectoryOrCreate
