apiVersion: v1
kind: Pod
metadata:
  name: pytorch-cifar10
spec:
  restartPolicy: Never
  containers:
  - image: pytorch_cifar10
    imagePullPolicy: IfNotPresent
    name: pytorch
    command: ["sh", "-c", "python -u cifar10.py; sleep infinity"]
    resources:
      requests:
        tencent.com/vcuda-core: "50"
        tencent.com/vcuda-memory: "20"
      limits:
        tencent.com/vcuda-core: "50"
        tencent.com/vcuda-memory: "20"
