apiVersion: v1
kind: Pod
metadata:
  name: conv
  annotations:
    tencent.com/vcuda-core-limit: "10"
spec:
  restartPolicy: Never
  containers:
  - image: bench-conv
    imagePullPolicy: IfNotPresent
    name: conv
    command: ["sh", "-c", "nvidia-smi -L; sleep infinity"]
    resources:
      requests:
        tencent.com/vcuda-core: "100"
      limits:
        tencent.com/vcuda-core: "100"
