apiVersion: v1
kind: Pod
metadata:
  name: conv
spec:
  restartPolicy: Never
  containers:
  - image: benchmark-conv
    imagePullPolicy: IfNotPresent
    name: conv
    resources:
      requests:
        tencent.com/vcuda-core: "100"
        tencent.com/vcuda-memory: "60"
      limits:
        tencent.com/vcuda-core: "100"
        tencent.com/vcuda-memory: "60"
